### PR TITLE
use multi-template

### PR DESCRIPTION
**Pull request by elevenbag**

### CODE REVIEW

**Comment by jeevatkm** [comment]
@elevenbag Can you please describe the goal of this change and how it's gonna be used? I'm not able to visualize it.

I'm currently working `v0.6` release preparation. v0.6 includes [view flexibility implementation](https://github.com/go-aah/aah/issues/50#issuecomment-304103576).

**Comment by elevenbag** [comment]
@jeevatkm 
load different themes (templates)。
`
Reply().HTMLf("/admin/index.html", data)
// resolve to template -> views/pages/admin/index.html

Reply().HTMLf("admin/index.html", data)
// resolve to template -> views/pages/frontend/app/admin/index.html
`
Now the changes。
aah.conf
`
view {
  theme_name = "default"
}
`

Reply().HTMLf("admin/index.html", data)
// resolve to template -> views/pages/frontend/default/app/admin/index.html

**Comment by jeevatkm** [comment]
Thanks for the details. Now I have an idea what you're trying to do.

Can you help me to document `theme_name = "default"` with sample syntax so that I will include it in the `v0.6` documentation?

**Comment by jeevatkm** [comment]
@elevenbag I'm merging this, will wait for documentation details.

**Comment by jeevatkm** [comment]
Just got an idea to make it better. Instead of single value from as `theme_name` from config. I'm thinking to add `HTMLltf(layout, theme, filename, data)` and `HTMLtf(theme, filename, data)`.

So this way it will be dynamic value. I will work on and coming in `v0.6` release.

**Comment by elevenbag** [comment]
@jeevatkm can remove ControllerName?I would like to specify their own tmpl ?


```
// # views/pages/<namespace-subpackage>/<theme_name>/app/index.html
tmplPath = filepath.Join(ctx.controller.Namespace, htmlRdr.Theme, tmplControllerName(ctx), tmplPath)
```

To achieve this effect
```
// # views/pages/<namespace-subpackage>/<theme_name>/index.html
tmplPath = filepath.Join(ctx.controller.Namespace, htmlRdr.Theme, tmplPath)
```

**Comment by jeevatkm** [comment]
@elevenbag First let me describe what are all options framework supports and my suggestion for your use case.

**Default behavior**
```
Method: HTML(data)
Layout: master.html
It resolves to views/pages/<namespace-subpackage>/<controller-name>/<action>.html
```

**To give an user full-controll over view rendering, framework provides**

```go
// To support layout
Method: HTMLl(layout, data)
Layout: <user-provided>
It resolves to views/pages/<namespace-subpackage>/<controller-name>/<action>.html

// To support custom filename, instead of default action name
Method: HTMLf(filename, data)
Layout: master.html
It resolves to views/pages/<namespace-subpackage>/<controller-name>/<user-provided-file>.html

// To support custom layout and filename
Method: HTMLlf(layout, filename, data)
Layout: <user-provided>
It resolves to views/pages/<namespace-subpackage>/<controller-name>/<user-provided-file>.html

// To support more than one action behavior file for the controller
Method: HTMLf(filename, data)  For e.g. HTMLf("user/custom.html", data)
Layout: master.html
It resolves to views/pages/<namespace-subpackage>/<controller-name>/<action>.html
E.g.: views/pages/<namespace-subpackage>/<controller-name>/user/custom.html

// To support custom structure between namespace and controller name (your PR)
Method: HTMLtf(theme, filename, data) and HTMLltf(layout, theme, filename, data)
Layout: <user-provided>
It resolves to views/pages/<namespace-subpackage>/<theme>/<controller-name>/<user-provided-file>.html

// Plus, filename param multi-behavior.
If `filename` param starts with `/` then framework uses as-is from pages directory.
It is applicable to all method which accepts `filename` parameter.
For e.g: HTMLf("/path/to/user/custom.html", data)  
It resolves to views/pages/path/to/user/custom.html
```

I believe it caters majority of the cases in the real world usage. It's good I documented all the scenario here. I will refer in the documentation. Thanks to you.

**Now, let's come to your use case** 
```go
// achieving this goal
views/pages/<namespace-subpackage>/<theme_name>/index.html
```
I would highly suggest you to create a Util Method to create `filename` param and supply it. Design your won directory structure under `pages`.

```go
// create a util method to compose `filename` param based on your use case (directory structure).
HTMLf("/path/to/template-file.html", data)
// It would resolve to views/pages/path/to/template-file.html
```

So removing controller name is not feasible, since it's default view resolve behavior.

Now, I have question to myself, does `theme` option HTML method is required?

**Comment by elevenbag** [comment]
`HTMLf `Solve my problem, thank you！

**Comment by jeevatkm** [comment]
You're welcome. Thanks for your confirmation. I will be reverting the theme option which I have added.

Mentioned `HTMLf` and `HTMLlf` changes getting released in `v0.6` in this week.

**Pull request merged**
