### PR TITLE
Request access log Implementation

### PR DESCRIPTION
**Pull request by adelowo**
Implementation of #69 feature.

### CODE REVIEW

**Comment by jeevatkm** [comment]
Nice work, can you please add test case for `initRequestAccessLog` method? This PR is feature getting added to the framework not a fix.

**Comment by adelowo** [comment]
Sure, I can

**Comment by adelowo** [comment]
HI @jeevatkm, what is the state of this PR

**Comment by jeevatkm** [comment]
This is ready to be merged, just I need to do my part.

**Comment by adelowo** [comment]
Thanks a lot

**Comment by jeevatkm** [comment]
you're welcome.

**Pull request merged**
